apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: gather-images-to-verify
spec:
  description: Extract images from deployment YAML to pass to EC for validation
  params:
    - name: IMAGE
      type: string
    - name: CI_PROJECT_URL
      type: string
    - name: GIT_REVISION
      type: string
  results:
    - name: IMAGES_TO_VERIFY
      description: >
        The images to be verified, in a format compatible with
        https://github.com/konflux-ci/build-definitions/tree/main/task/verify-enterprise-contract/0.1.
        When there are no images to verify, this is an empty string.
  steps:
    - script: |
        tee $(results.IMAGES_TO_VERIFY.path) <<EOF
        {
          "components": [
            {
              "containerImage": "$(params.IMAGE)",
              "source": {
                "git": {
                  "url": "$(params.CI_PROJECT_URL)",
                  "revision": "$(params.GIT_REVISION)"
                }
              }
            }
          ]
        }
        EOF
      image: 'ubi8/ubi-minimal'
      name: create-images-yaml
      resources: {}
