# Konflux ReleasePlanAdmission for DEVELOPMENT Environment
# This goes in the tssc-app-development namespace (SHARED, NOT per-app)
# It accepts releases FROM tssc-app-ci for ALL applications

apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlanAdmission
metadata:
  name: accept-releases
  namespace: tssc-app-development  # FIXED: Shared development namespace
  annotations:
    description: "Accept releases from tssc-app-ci to development environment"
spec:
  # Accept releases from CI namespace
  origin: tssc-app-ci

  # NO applications filter - accepts ALL apps (multi-tenant)
  # applications field is OMITTED intentionally

  # Environment identifier
  environment: development

  # Pipeline runs in tssc-app-ci (cross-namespace reference)
  pipelineRef:
    name: release-pipeline
    namespace: tssc-app-ci  # Pipeline is in CI namespace

  # Service account (must have cross-namespace permissions)
  serviceAccount: release-service-account

  # Enterprise Contract policy configuration
  data:
    enterpriseContract:
      # Policy for development (relaxed - just warnings)
      policy: "github.com/enterprise-contract/config//slsa3"
      publicKey: "k8s://openshift-pipelines/signing-secrets"
      strict: "false"  # Don't block, just warn in development

---
# How to apply (ONE-TIME SETUP - not per app):
# 1. Apply to the SHARED development namespace:
#    oc apply -f release-plan-admission-dev.yaml -n tssc-app-development
#
# 2. Verify:
#    oc get releaseplanadmission accept-releases -n tssc-app-development
#
# Important:
# - This is created ONCE for the shared environment
# - NOT per-application (accepts ALL apps from tssc-app-ci)
# - All applications deploy to tssc-app-development namespace
# - strict: "false" - development allows images with policy warnings
